### PR TITLE
v3 new config fix compatibility

### PR DESCRIPTION
**Pull request by jaumard**
Need new version of trails merge/publish (https://github.com/trailsjs/trails/pull/317)

### CODE REVIEW

**Comment by scott-wyatt** [comment]
Just curious, why use `app.once` instead of the trailpack lifecycle?

**Comment by jaumard** [comment]
You're listening a trails event so it's not part of the trailpack lifecycle, it's like the start/stop event

**Comment by scott-wyatt** [comment]
Gotcha, looks fine to be then.

**Review by scott-wyatt — APPROVED** [review]

**Comment by jaumard** [comment]
Cool so we need to take care of the other one first, then this one :)

**Pull request merged**
